### ISSUE TITLE
Typo. But also maybe lets follow the structure used in solenoid.go and implement String() on each object for pretty printing

### ISSUE THREAD

**Issue by dtp263** [dtp263/GoFire#8]
Typo. But also maybe lets follow the structure used in solenoid.go and implement String() on each object for pretty printing

_Originally posted by @dtp263 in https://github.com/dtp263/GoFire/pull/6_

**Comment by twoshark** [comment]
Typo Fixed and moved to String() method for the whole object and a State() method to return just state
